name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    # Step 4: Deploy to Streamlit
    - name: Deploy to Streamlit
      run: |
        streamlit run Chatbot.py  # filename
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Access the secret API key securely
